/* =====================================================================
   meta-design: icons
   ---------------------------------------------------------------------
   One geometry per icon, many styles. Geometry is a 48x48 line drawing
   registered once into a hidden <svg><defs>. A *style* is a renderer
   that instantiates that geometry in a different way:

     line    the plain outline the page was drawn with
     flat    filled shapes on a tinted disc
     3d      extruded parcel-label look in the brand palette
     3d-dpd  the same extrusion in a courier red / navy palette
     emoji   text fallback, no SVG at all (handy for e-mail or plain skins)

   Which style an icon uses is a *declaration*, resolved in this order:
     1. the `variant` attribute on <md-icon>
     2. the CSS custom property --icon-<name> on the element or any ancestor
        e.g.  .step { --icon-box: "3d-dpd"; }
     3. the CSS custom property --icon-style (page/skin default)

   Geometry is generated by scripts/fetch-icons.cjs (`npm run icons`) from
   openly licensed sets, rescaled from their native grid to 48x48; each
   entry's `src` names the origin. Do not hand-edit the GEOMETRY block.

     hugeicons:*   Hugeicons stroke-rounded, MIT. Copyright (c) 2024 Hugeicons.
                   https://github.com/hugeicons/hugeicons-react/blob/main/LICENSE
     tabler:*      Tabler Icons, MIT. Copyright (c) 2020-2024 Paweł Kuna.
                   https://github.com/tabler/tabler-icons/blob/main/LICENSE
     streamline:*  Streamline Core (free set), CC BY 4.0, by Streamline
                   (https://streamlinehq.com). Attribution required.
   ===================================================================== */
(function (MD) {
  const GEOMETRY = {
    duvet:          { emoji: "🛏️", src: "hugeicons:bed-single-01", g: '<path d="M44 35H4M44 42v-10c0-3.77 0-5.66-1.17-6.83S39.77 24 36 24H12c-3.77 0-5.66 0-6.83 1.17S4 28.23 4 32v10"/><path d="M32 24v-2.76c0-1.02-.18-1.35-1.12-1.75C28.93 18.65 26.56 18 24 18s-4.93 .65-6.88 1.48c-.94 .4-1.12 .74-1.12 1.76V24"/><path d="M40 24V14.72c0-1.38 0-2.07-.34-2.73c-.34-.65-.83-.99-1.8-1.67A24.2 24.2 0 0 0 24 6c-5.15 0-9.93 1.6-13.86 4.33c-.97 .68-1.46 1.01-1.8 1.67S8 13.34 8 14.72V24"/>' },
    pillow:         { emoji: "🛌", src: "tabler:pillow", g: '<path d="M12 18a18.68 18.68 0 0 1 0 12"/><path d="M43.4 33.21c.96 1.87 .56 4.18-.97 5.58c-1.53 1.41-3.8 1.54-5.48 .33a96 96 0 0 1-25.89 0a4.32 4.32 0 0 1-5.48-.33a4.69 4.69 0 0 1-.97-5.58a83.4 83.4 0 0 1 0-18.33a4.69 4.69 0 0 1 .87-5.71a4.32 4.32 0 0 1 5.59-.29a96 96 0 0 1 25.89 0a4.32 4.32 0 0 1 5.59 .29c1.56 1.45 1.92 3.84 .87 5.71a83.4 83.4 0 0 1 0 18.33"/>' },
    sheet:          { emoji: "🧻", src: "hugeicons:bed-double", g: '<path d="M44 35H4M44 42v-10c0-3.77 0-5.66-1.17-6.83S39.77 24 36 24H12c-3.77 0-5.66 0-6.83 1.17S4 28.23 4 32v10"/><path d="M22 24v-3.57c0-.76-.11-1.02-.7-1.32C20.08 18.49 18.6 18 17 18s-3.08 .49-4.3 1.11c-.59 .3-.7 .56-.7 1.32V24m24 0v-3.57c0-.76-.11-1.02-.7-1.32C34.08 18.49 32.6 18 31 18s-3.08 .49-4.3 1.11c-.59 .3-.7 .56-.7 1.32V24"/><path d="M42 24V14.72c0-1.38 0-2.07-.38-2.73s-.93-.99-2.03-1.67C35.17 7.6 29.8 6 24 6s-11.17 1.6-15.59 4.33c-1.1 .68-1.64 1.01-2.03 1.67S6 13.34 6 14.72V24"/>' },
    towel:          { emoji: "🧖", src: "hugeicons:towels", g: '<path d="M13 10H30c3.77 0 5.66 0 6.83 1.17S38 14.23 38 18v6c0 3.77 0 5.66-1.17 6.83S33.77 32 30 32h-6c-3.77 0-5.66 0-6.83-1.17S16 27.77 16 24V16M13 10A3 3 0 0 0 10 13V16h6M13 10A3 3 0 0 1 16 13V16m18 16c0 3.77 0 5.66-1.17 6.83S29.77 40 26 40H18c-3.77 0-5.66 0-6.83-1.17S10 35.77 10 32v-10m34-14v2c0 1.86 0 2.8-.3 3.53a4 4 0 0 1-2.17 2.17C40.8 16 39.86 16 38 16M4 8v2c0 1.86 0 2.8 .3 3.53a4 4 0 0 0 2.17 2.17C7.2 16 8.14 16 10 16"/>' },
    plate:          { emoji: "🍽️", src: "hugeicons:plate", g: '<path d="M36.86 26c.72 1.03 1.14 2.29 1.14 3.66C38 33.16 35.2 36 31.75 36q-.92 0-1.75-.25M37.96 20c3.61 2.04 6.04 5.85 6.04 10.21C44 36.72 38.6 42 31.93 42A12.2 12.2 0 0 1 24 39.1"/><circle cx="18" cy="20" r="8"/><circle cx="18" cy="20" r="14"/>' },
    mug:            { emoji: "☕", src: "hugeicons:coffee-02", g: '<path d="M36.5 21h2.78c3.7 0 4.8 .53 4.71 3.17c-.15 4.37-2.12 9.44-9.99 10.83"/><path d="M11.89 41.23C5.14 36.04 4.15 28.68 4 21c-.06-3.32 .9-4 5.32-4h21.36c4.42 0 5.38 .68 5.32 4c-.15 7.68-1.14 15.04-7.89 20.23c-1.92 1.48-3.54 1.77-6.27 1.77H18.16c-2.73 0-4.35-.29-6.27-1.77Z"/><path d="M22.62 5C21.52 5.68 20 8 20 11M15.08 8S14 9 14 11M28 8c-.55 .34-1 2-1 3"/>' },
    cutlery:        { emoji: "🍴", src: "hugeicons:spoon-and-fork", g: '<path d="m44 13l-6.88 6.88a3 3 0 0 1-4.24 0l-1.38-1.38l-1.38-1.38a3 3 0 0 1 0-4.24l6.88-6.88m-5.5 12.5L8 42M40 10l-5 5"/><path d="M15.98 17.98c-2.39 2.39-5.67 2.99-8.65 0S2.78 9.56 5.16 7.17C7.55 4.78 12.99 6.34 15.98 9.33s2.39 6.26 0 8.65Zm0 0L40 42M18.41 4.79A20 20 0 0 1 24 4c2.3 0 4.52 .39 6.58 1.11M4.1 22Q4 22.99 4 24c0 4.06 1.21 7.84 3.29 11m8.25 7.13c2.57 1.2 5.43 1.87 8.45 1.87a20 20 0 0 0 8.52-1.9m8.18-7.1A19.9 19.9 0 0 0 44 24q0-1.74-.29-3.39"/>' },
    pan:            { emoji: "🍳", src: "hugeicons:pan-01", g: '<path d="M39.61 29.61A15 15 0 1 1 18.39 8.39a15 15 0 0 1 21.21 21.21Z"/><path d="M34.66 24.66a8 8 0 1 1-11.31-11.31a8 8 0 0 1 11.31 11.31ZM22 31.94c-5.46 1.55-7.03 7.03-10.83 10.83a4.2 4.2 0 1 1-5.94-5.94c3.8-3.8 9.28-5.36 10.83-10.83"/>' },
    kettle:         { emoji: "🫖", src: "hugeicons:kettle-01", g: '<path d="m14 14l-4.32 .99c-3.01 .69-4.51 1.03-5.25 2.31s-.42 2.99 .23 6.42l.89 4.75C6.39 32.97 8.69 34.49 12 36M14.28 15.56l-2.06 21.6c-.3 3.2-.46 4.8 .61 5.82C13.91 44 15.74 44 19.41 44h13.18c3.67 0 5.5 0 6.57-1.02c1.07-1.02 .92-2.62 .61-5.82l-2.06-21.6C37.08 8.88 32.16 6 26 6S14.92 8.88 14.28 15.56Z"/><path d="M16 14h25.96c1.72 0 2.32 .46 1.93 2.48c-.65 3.43-2.6 6.22-5.18 7.52"/><path d="M24 34c0-6 4-4 4-10m-2-18V4"/>' },
    board:          { emoji: "🔪", src: "hugeicons:knife-01", g: '<path d="M30.2 33.49c5.58-6.05 9.45-10.83 11.88-14.09c1.33-1.78 1.99-2.67 1.91-3.89C43.84 12.98 37.45 6 34.64 6c-1.29 0-2.32 1.07-4.39 3.22L5.1 35.34a4.01 4.01 0 0 0 0 5.51c1.66 1.73 4.43 1.46 5.75-.56l4.58-6.95c1.84-2.79 3.15-2.8 5.36-.52c1.33 1.38 3.01 3.96 5.11 3.93c1.31-.02 2.31-1.1 4.31-3.28"/><path d="M36.25 16H36m.5 0a.5 .5 0 1 1-1 0a.5 .5 0 0 1 1 0"/>' },
    plug:           { emoji: "🔌", src: "hugeicons:plug-01", g: '<path d="M31 4v8m-14 0V4"/><path d="M12.01 15.23C11.87 13.49 13.28 12 15.06 12h17.88c1.78 0 3.19 1.49 3.05 3.23l-.37 4.76a19.8 19.8 0 0 1-3.36 9.57l-1.2 1.77A6.16 6.16 0 0 1 25.97 34h-3.94a6.16 6.16 0 0 1-5.09-2.68l-1.2-1.77a19.8 19.8 0 0 1-3.36-9.57z"/><path d="M24 34v10M22 18h4"/>' },
    bag:            { emoji: "🧺", src: "hugeicons:shopping-bag-02", g: '<path d="m35 17.5l-4.91 21.61a3.6 3.6 0 0 0 3.51 4.39H36"/><path d="M38.44 43.5H9.56a3.56 3.56 0 0 1-3.45-4.43l4.38-17.51c.73-2.91 1.09-4.37 2.18-5.21c1.08-.85 2.58-.85 5.58-.85h11.51c3 0 4.5 0 5.58 .85c1.09 .85 1.45 2.3 2.18 5.21l4.38 17.51a3.56 3.56 0 0 1-3.46 4.43"/><path d="M30 15.5v-4a6 6 0 1 0-12 0v4m2 6h5"/>' },
    bottle:         { emoji: "🔥", src: "hugeicons:fire", g: '<path d="M27.71 44c24.44-6 10.76-30-5.87-40c-1.96 7-4.89 9-10.76 16c-7.77 9.27-3.91 20 6.84 24c-1.63-2-5.83-6.2-2.93-12c1-2 3-4 2-8c1.96 1 6 2 7 7c1.63-2 3.32-6.2 1.76-11c12.24 9 7.24 18 1.96 24"/>' },
    thermal:        { emoji: "👕", src: "hugeicons:long-sleeve-shirt", g: '<path d="M11 14c.66 1.97 1.44 3.97 1.72 6.04c.2 1.49 .12 2.99-.04 6.01L12 39.05c0 1.41 .24 2.16 1.51 2.85c5.23 2.8 15.75 2.8 20.98 0c1.27-.68 1.51-1.44 1.51-2.85l-.68-13c-.16-3.02-.24-4.52-.04-6.01c.28-2.07 1.06-4.07 1.72-6.04"/><path d="M11.94 37.03c-.93 .47-1.86 1.07-2.95 .96c-1.83-.2-2.26-1.08-2.63-3.3L4.2 21.84c-.29-1.72-.29-1.73 .17-3.41l1.08-3.97c.73-2.68 1.09-4.03 1.96-5.05c.87-1.02 2.14-1.6 4.69-2.75L17.18 4.36c.79-.36 .8-.36 1.66-.36h10.31c.87 0 .87 0 1.66 .36l5.09 2.3c2.54 1.15 3.81 1.73 4.69 2.75c.87 1.02 1.24 2.37 1.96 5.05l1.08 3.97c.46 1.68 .46 1.7 .17 3.41l-2.16 12.84c-.37 2.22-.8 3.1-2.64 3.3c-1.13 .12-1.96-.47-2.95-.96"/><path d="M18 5s1.82 3.83 3.32 4.63c.77 .41 1.74 .37 2.68 .37s1.91 .04 2.68-.37C28.18 8.83 30 5 30 5"/>' },
    socks:          { emoji: "🧦", src: "hugeicons:socks", g: '<path d="M27 12V10c0-1.89 0-2.83 .59-3.41S29.11 6 31 6h6c1.89 0 2.83 0 3.41 .59S41 8.11 41 10v2zm14 0v14.68a8 8 0 0 1-2.35 5.66l-7.62 7.59a7.05 7.05 0 0 1-9.97 0a7.04 7.04 0 0 1 0-9.96L27 24V12m-6 0h-6V10c0-1.89 0-2.83 .59-3.41S17.11 6 19 6h2m-6 6v12l-5.94 5.98a7.04 7.04 0 0 0 0 9.96a7.04 7.04 0 0 0 5.94 2M22 29l10 10m-22-10l4 4"/><path d="M41 24a6 6 0 0 0-4.47 10"/>' },
    beanie:         { emoji: "🧢", src: "streamline:beanie", g: '<path d="M42.86 36h-37.71a3.43 3.43 0 0 0-3.43 3.43v3.43a3.43 3.43 0 0 0 3.43 3.43h37.71a3.43 3.43 0 0 0 3.43-3.43v-3.43a3.43 3.43 0 0 0-3.43-3.43m-37.71 0v-10.29a18.86 18.86 0 1 1 37.71 0v10.29M24 6.86V1.71"/>' },
    vitamin:        { emoji: "💊", src: "hugeicons:pill", g: '<path d="m22.9 39.1l16.2-16.2a9.9 9.9 0 0 0-14-14l-16.2 16.2a9.9 9.9 0 1 0 14 14M17 17l14 14"/>' },
    mask:           { emoji: "😴", src: "hugeicons:sleeping", g: '<path d="M26 4.1Q25.01 4 24 4C12.95 4 4 12.95 4 24s8.95 20 20 20s20-8.95 20-20q0-2.06-.4-4"/><path d="M20 22H17.41c-.91 0-1.77-.36-2.41-1m13 1h2.59c.91 0 1.77-.36 2.41-1"/><circle cx="24" cy="32" r="4"/><path d="M34 4h5.89c1.24 0 1.86 0 2.03 .4s-.26 .88-1.1 1.84l-4.85 5.52c-.84 .96-1.27 1.44-1.1 1.84s.78 .4 2.02 .4H42"/>' },
    tea:            { emoji: "🍵", src: "hugeicons:tea", g: '<path d="M36.5 21h2.78c3.7 0 4.8 .53 4.71 3.17c-.15 4.37-2.12 9.44-9.99 10.83"/><path d="M11.89 41.23C5.14 36.04 4.15 28.68 4 21c-.06-3.32 .9-4 5.32-4h21.36c4.42 0 5.38 .68 5.32 4c-.15 7.68-1.14 15.04-7.89 20.23c-1.92 1.48-3.54 1.77-6.27 1.77H18.16c-2.73 0-4.35-.29-6.27-1.77Z"/><path d="M20 17v10m-2.99 5.59l.58-3.7c.17-1.08 1.2-1.89 2.41-1.89c1.21 0 2.23 .81 2.4 1.89l.58 3.7c.32 1.99-6.25 1.75-5.98 0M22.62 5C21.52 5.68 20 8 20 11M15.08 8S14 9 14 11M28 8c-.55 .34-1 2-1 3"/>' },
    rowie:          { emoji: "🥐", src: "hugeicons:croissant", g: '<path d="M7.01 20.99c-.91 .92-1.56 2.66-2.66 6.66c-.23 .85-.41 1.72-.33 2.59c.12 1.3 .56 2.1 1.44 2.76c.94 .71 2.15 .88 3.33 .88h3.04c2.09 0 4.29-.41 5.7-1.96c1.6-1.75 2.01-3.7 1.51-4.99m1-19.84l6.7-2.65c2.05-.81 4.51-.58 6.01 1.03c.73 .78 1.19 1.57 1.33 2.61v4.13c0 2.41-1.04 4.79-3.13 6.03c-1.2 .71-2.36 1.21-3.89 1.75M8.01 16.03c2.41-4.3 4.15-6.06 8.02-7.94c.88-.48 1.62-.75 2.32-.8c2.79-.19 4.28 3.09 5.42 5.62l2.02 4.49c.18 .41 .32 .83 .39 1.27c.31 2 .01 3-1.12 4.3l-1.83 1.81c-.78 .77-1.61 1.55-2.66 1.87q-.44 .14-.86 .15c-1.87 .07-3.63-.94-5.4-1.55c-2.26-.79-3.94-2.06-6.28-4.27c-1.24-1.97-1.18-3.06 0-4.96m26.07-.94c2.35 .41 3.68 .65 6.01 1c.92 .13 1.6 .01 2.37-.51c1.19-.8 1.85-2.32 1.39-3.67c-.45-1.33-1.56-2.38-3.76-3.79c-2.31-1.6-3.62-2.27-6.02-2.99M5 34.02c.19 2.78 1.16 4.55 4.01 7.97c1.29 1.32 2.23 1.87 3.48 2c.98 .1 1.93-.37 2.55-1.14c.76-.94 1.06-1.71 .99-2.85l-1-5.98"/>' },
    lamp:           { emoji: "💡", src: "hugeicons:lamp-desk", g: '<path d="M15.5 24.88a4 4 0 1 1-8 0a4 4 0 0 1 8 0Z"/><path d="m13.5 22.88l10-11"/><path d="M13.5 42.88h18Zm0-14l9 9m7.76-30.01l-1.26-1.28c-.53-.53-.79-.8-1.05-.97a3 3 0 0 0-3.3 0c-.26 .17-.53 .44-1.05 .97c-.51 .52-.77 .78-.94 1.04a3 3 0 0 0 0 3.25c.17 .26 .42 .52 .94 1.04l1.34 1.36c-.47 1.43-.96 4.86-.04 7.93c.41 1.39 .62 2.08 1.72 2.36c1.11 .28 1.77-.4 3.11-1.75l9.03-9.17c1.3-1.32 1.95-1.98 1.68-3.07s-.94-1.3-2.28-1.72c-3.05-.97-6.48-.47-7.9 .01"/><path d="M37.5 13.88a5 5 0 1 1-7 7"/>' },
    rack:           { emoji: "👚", src: "hugeicons:hanger", g: '<path d="m8.25 30.73l12-6.75A7.4 7.4 0 0 1 24 23a7.4 7.4 0 0 1 3.74 .98l12 6.75a4.42 4.42 0 0 1-2.16 8.27H10.42a4.42 4.42 0 0 1-2.16-8.27"/><path d="M20 12.81c0-2.1 1.79-3.81 4-3.81s4 1.71 4 3.81c0 1.44-.84 2.69-2.08 3.34c-.98 .51-1.92 1.36-1.92 2.47v4.38"/>' },
    topper:         { emoji: "🛏️", src: "hugeicons:bed", g: '<path d="M4 7v34m40-24v24M4 17l8 4h32m-40 10h8m32 0h-6m-26-10v12c0 3.31 .69 4 4 4h18c3.31 0 4-.69 4-4v-12"/><path d="M13.63 21c.16-.85 .41-1.74 .36-2.61a4.12 4.12 0 0 0-1.74-3.17c-.4-.28-1.29-.56-2.23-.81c-1.36-.35-2.05-.53-2.84-.35c-.57 .13-1.06 .43-1.76 .97c-.08 .06-.12 .09-.18 .14A4.2 4.2 0 0 0 4 17"/>' },
    box:            { emoji: "📦", src: "hugeicons:package", g: '<path d="M24 44c-1.64 0-3.2-.66-6.33-1.98C9.89 38.73 6 37.09 6 34.32V14m18 30c1.64 0 3.2-.66 6.33-1.98C38.11 38.73 42 37.09 42 34.32V14m-18 30V22.71M16.65 19.38L10.81 16.56C7.6 15 6 14.23 6 13s1.6-2 4.81-3.56l5.84-2.83C20.26 4.87 22.06 4 24 4s3.74 .87 7.35 2.62l5.84 2.83C40.4 11 42 11.77 42 13s-1.6 2-4.81 3.56l-5.84 2.83C27.74 21.13 25.94 22 24 22s-3.74-.87-7.35-2.62M12 24l4 2m18-18L14 18"/>' },
    chat:           { emoji: "💬", src: "hugeicons:bubble-chat", g: '<path d="M43 24a19 19 0 0 1-19 19c-3.26 0-6.32-.82-9-2.26c-3.74-2.01-6.25-.14-8.47 .19a1.06 1.06 0 0 1-.91-.31a1.28 1.28 0 0 1-.23-1.41c.87-2.05 1.67-5.94 .58-9.21a19 19 0 0 1-.97-6a19 19 0 1 1 38 0"/><path d="M24.25 24H24m-7.75 0H16m16.25 0H32m-7.5 0a.5 .5 0 1 1-1 0a.5 .5 0 0 1 1 0m-8 0a.5 .5 0 1 1-1 0a.5 .5 0 0 1 1 0m16 0a.5 .5 0 1 1-1 0a.5 .5 0 0 1 1 0"/>' },
    mix:            { emoji: "🧩", src: "hugeicons:puzzle", g: '<path d="M25.66 12a6 6 0 1 0-11.32 0c-4.57 .02-7.01 .18-8.58 1.76S4.02 17.77 4 22.34a6 6 0 1 1 0 11.32c.02 4.57 .18 7.01 1.76 8.58s4.01 1.74 8.58 1.76a6 6 0 1 1 11.32 0c4.57-.02 7.01-.18 8.58-1.76s1.74-4.01 1.76-8.58a6 6 0 1 0 0-11.32c-.02-4.57-.18-7.01-1.76-8.58c-1.58-1.58-4.01-1.74-8.58-1.76Z"/>' },
    key:            { emoji: "🔑", src: "hugeicons:key-01", g: '<path d="M31 29a12 12 0 1 0-10.94-7.06L5 37v6h6v-4h4v-4h4l7.06-7.06c1.51 .68 3.18 1.06 4.94 1.06m4-16l-2 2"/>' },
    sun:            { emoji: "☀️", src: "hugeicons:sun-03", g: '<path d="M34 24a10 10 0 1 1-20 0a10 10 0 0 1 20 0Z"/><path d="M24 4v3m0 34V44m14.14-5.86l-2.12-2.12M11.98 11.98L9.86 9.86M44 24h-3m-34 0H4m34.14-14.14l-2.12 2.12M11.98 36.02l-2.12 2.12"/>' },
    moon:           { emoji: "🌙", src: "hugeicons:moon-02", g: '<path d="M43 28.16A17.11 17.11 0 0 1 19.84 5C11.34 6.99 5 14.63 5 23.75a19.25 19.25 0 0 0 19.25 19.25c9.12 0 16.75-6.34 18.75-14.84"/>' },
    auto:           { emoji: "🌗", src: "hugeicons:contrast", g: '<circle cx="24" cy="24" r="20"/><path d="M24 44V4"/><path d="M24 14h17M24 34h17M24 24h20"/>' },
    globe:          { emoji: "🌐", src: "hugeicons:globe-02", g: '<circle cx="24" cy="24" r="20"/><path d="M16 24c0 12 8 20 8 20s8-8 8-20s-8-20-8-20s-8 8-8 20Z"/><path d="M42 30H6m36-12H6"/>' },
    brush:          { emoji: "🎨", src: "hugeicons:paint-board", g: '<path d="M44 24c0-11.05-8.95-20-20-20S4 12.95 4 24s8.95 20 20 20c1.68 0 4 .23 4-2c0-1.22-.63-2.16-1.26-3.09c-.92-1.37-1.83-2.72-.74-4.91c1.33-2.67 3.56-2.67 6.96-2.67c1.7 0 3.7 0 6.04-.33c4.2-.6 5-3.18 5-7Z"/><circle cx="19" cy="17" r="3"/><circle cx="33" cy="19" r="3"/><path d="M14.25 30H14m.5 0a.5 .5 0 1 1-1 0a.5 .5 0 0 1 1 0"/>' },
    card:           { emoji: "💳", src: "hugeicons:credit-card", g: '<path d="M4 24c0-7.07 0-10.61 2.11-12.97q.51-.57 1.11-1.04C9.72 8 13.48 8 21 8h6c7.52 0 11.28 0 13.78 1.98q.6 .48 1.11 1.05C44 13.39 44 16.93 44 24s0 10.61-2.11 12.97a8.8 8.8 0 0 1-1.11 1.04C38.28 40 34.52 40 27 40h-6c-7.52 0-11.28 0-13.79-1.98a8.8 8.8 0 0 1-1.11-1.05C4 34.61 4 31.07 4 24"/><path d="M20 32h3m6 0H36"/><path d="M4 18h40"/>' },
    "kit-arrival":  { emoji: "🛏️", src: "alias:duvet", g: '<path d="M44 35H4M44 42v-10c0-3.77 0-5.66-1.17-6.83S39.77 24 36 24H12c-3.77 0-5.66 0-6.83 1.17S4 28.23 4 32v10"/><path d="M32 24v-2.76c0-1.02-.18-1.35-1.12-1.75C28.93 18.65 26.56 18 24 18s-4.93 .65-6.88 1.48c-.94 .4-1.12 .74-1.12 1.76V24"/><path d="M40 24V14.72c0-1.38 0-2.07-.34-2.73c-.34-.65-.83-.99-1.8-1.67A24.2 24.2 0 0 0 24 6c-5.15 0-9.93 1.6-13.86 4.33c-.97 .68-1.46 1.01-1.8 1.67S8 13.34 8 14.72V24"/>' },
    "kit-winter":   { emoji: "🔥", src: "alias:bottle", g: '<path d="M27.71 44c24.44-6 10.76-30-5.87-40c-1.96 7-4.89 9-10.76 16c-7.77 9.27-3.91 20 6.84 24c-1.63-2-5.83-6.2-2.93-12c1-2 3-4 2-8c1.96 1 6 2 7 7c1.63-2 3.32-6.2 1.76-11c12.24 9 7.24 18 1.96 24"/>' },
    "kit-both":     { emoji: "📦", src: "alias:box", g: '<path d="M24 44c-1.64 0-3.2-.66-6.33-1.98C9.89 38.73 6 37.09 6 34.32V14m18 30c1.64 0 3.2-.66 6.33-1.98C38.11 38.73 42 37.09 42 34.32V14m-18 30V22.71M16.65 19.38L10.81 16.56C7.6 15 6 14.23 6 13s1.6-2 4.81-3.56l5.84-2.83C20.26 4.87 22.06 4 24 4s3.74 .87 7.35 2.62l5.84 2.83C40.4 11 42 11.77 42 13s-1.6 2-4.81 3.56l-5.84 2.83C27.74 21.13 25.94 22 24 22s-3.74-.87-7.35-2.62M12 24l4 2m18-18L14 18"/>' },
    "kit-mix":      { emoji: "🧩", src: "alias:mix", g: '<path d="M25.66 12a6 6 0 1 0-11.32 0c-4.57 .02-7.01 .18-8.58 1.76S4.02 17.77 4 22.34a6 6 0 1 1 0 11.32c.02 4.57 .18 7.01 1.76 8.58s4.01 1.74 8.58 1.76a6 6 0 1 1 11.32 0c4.57-.02 7.01-.18 8.58-1.76s1.74-4.01 1.76-8.58a6 6 0 1 0 0-11.32c-.02-4.57-.18-7.01-1.76-8.58c-1.58-1.58-4.01-1.74-8.58-1.76Z"/>' },
  };

  const PALETTES = {
    "3d":     { fill: "var(--icon-fill)", top: "var(--icon-fill-2)", depth: "var(--icon-depth)", stroke: "var(--icon-stroke)", shadow: "var(--icon-shadow)" },
    "3d-dpd": { fill: "#DC0032", top: "#FF5C7A", depth: "#7A0020", stroke: "#1E1E3C", shadow: "rgba(30,30,60,.35)" },
  };

  // ---- renderers ---------------------------------------------------
  const svgOpen = (cls, extra = "") =>
    `<svg viewBox="0 0 48 48" class="md-ico ${cls}" aria-hidden="true" focusable="false" ${extra}>`;

  const STYLES = {
    line(name) {
      return svgOpen("md-ico--line") +
        `<use href="#i-${name}" fill="none" stroke="var(--icon-stroke)" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
    },
    flat(name) {
      return svgOpen("md-ico--flat") +
        `<circle cx="24" cy="24" r="23" fill="var(--icon-fill-2)"/>` +
        `<use href="#i-${name}" style="--md-shape-fill: var(--icon-fill)" fill="none" stroke="var(--icon-stroke)" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
    },
    "3d"(name, pal = PALETTES["3d"]) {
      const dark = pal.depth, layers = [];
      // extrusion: stack of offset copies down and to the right
      for (let i = 3; i >= 1; i--) {
        layers.push(`<use href="#i-${name}" transform="translate(${i} ${i})" style="--md-shape-fill:${dark};--md-path-fill:${dark}" fill="none" stroke="${dark}" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>`);
      }
      return svgOpen("md-ico--3d") +
        `<ellipse cx="26" cy="44" rx="18" ry="3.5" fill="${pal.shadow}"/>` +
        layers.join("") +
        `<use href="#i-${name}" style="--md-shape-fill:${pal.fill};--md-path-fill:${pal.fill}" fill="none" stroke="${pal.stroke}" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>` +
        `<use href="#i-${name}" transform="translate(-1 -1) scale(.98)" style="--md-shape-fill:${pal.top};--md-path-fill:${pal.top}" fill="none" stroke="none" opacity=".35"/>` +
        `</svg>`;
    },
    "3d-dpd"(name) { return STYLES["3d"](name, PALETTES["3d-dpd"]); },
    emoji(name) {
      const e = (GEOMETRY[name] || {}).emoji || "•";
      return `<span class="md-ico md-ico--emoji" aria-hidden="true" style="font-size:.9em;line-height:1">${e}</span>`;
    },
    // Rendered image themes, cut to web/img/icons/<theme>/<name>.webp by
    // scripts/photo-icons-webp.cjs from the masters in assets/icons/:
    //   photo          photorealistic product shots (assets/icons/photorealistic-icons)
    //   skeuomorphic   the 3D renders from scripts/gen-photo-icons.sh (assets/icons/skeuomorphic)
    // A missing file falls back to the next theme and finally to the line drawing,
    // so partial coverage (the photorealistic set has no kit or add-on icons yet)
    // degrades gracefully instead of showing a broken image.
    photo(name) { return imageIcon(name, ["photorealistic", "skeuomorphic"]); },
    skeuomorphic(name) { return imageIcon(name, ["skeuomorphic", "photorealistic"]); },
  };
  function imageIcon(name, themes) {
    const [theme, ...rest] = themes;
    const next = rest.length ? `MD.icons.renderImage('${name}', ${JSON.stringify(rest)})` : `MD.icons.render('${name}', 'line')`;
    return `<span class="md-ico md-ico--photo md-ico--${theme}">` +
      `<img src="/img/icons/${theme}/${name}.webp" alt="" loading="lazy" decoding="async" width="256" height="256" ` +
      `onerror="this.parentElement.outerHTML = ${next.replace(/"/g, '&quot;')}">` +
      `</span>`;
  }
  STYLES.photorealistic = STYLES.photo;
  STYLES["3d-dpd-style"] = STYLES["3d-dpd"];
  STYLES["3D-dpd-style"] = STYLES["3d-dpd"];

  // ---- registry ----------------------------------------------------
  function mountDefs() {
    if (document.getElementById("md-icon-defs")) return;
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.id = "md-icon-defs";
    svg.setAttribute("width", "0"); svg.setAttribute("height", "0");
    svg.setAttribute("style", "position:absolute"); svg.setAttribute("aria-hidden", "true");
    svg.innerHTML = "<defs>" + Object.entries(GEOMETRY).map(([k, v]) => `<g id="i-${k}">${v.g}</g>`).join("") + "</defs>";
    document.body.prepend(svg);
  }

  function normaliseStyle(s) {
    s = String(s || "").trim().replace(/^["']|["']$/g, "").toLowerCase();
    if (s.endsWith("-style")) s = s.slice(0, -6);
    return STYLES[s] ? s : "";
  }

  // Resolve the style declared for an icon on a given element via CSS custom properties.
  function declaredStyle(el, name) {
    const cs = getComputedStyle(el);
    return normaliseStyle(cs.getPropertyValue("--icon-" + name)) || normaliseStyle(cs.getPropertyValue("--icon-style")) || "line";
  }

  function render(name, style) {
    if (!GEOMETRY[name]) name = "box";
    const fn = STYLES[normaliseStyle(style) || "line"];
    return fn(name);
  }

  // <md-icon name="box" variant="3d-dpd" size="l"></md-icon>
  class MdIcon extends HTMLElement {
    static get observedAttributes() { return ["name", "variant"]; }
    connectedCallback() { this.paint(); }
    attributeChangedCallback() { if (this.isConnected) this.paint(); }
    paint() {
      const name = this.getAttribute("name") || "box";
      const style = normaliseStyle(this.getAttribute("variant")) || declaredStyle(this, name);
      if (this.dataset.painted === name + "|" + style) return;
      this.dataset.painted = name + "|" + style;
      this.innerHTML = render(name, style);
    }
  }
  if (!customElements.get("md-icon")) customElements.define("md-icon", MdIcon);

  MD.icons = {
    GEOMETRY, STYLES, PALETTES, mountDefs, render, declaredStyle, normaliseStyle,
    names: () => Object.keys(GEOMETRY),
    styles: () => ["line", "flat", "3d", "3d-dpd", "emoji", "photo", "skeuomorphic"],
    renderImage: imageIcon,
    // string helper for templates: MD.icons.tag("box", {size:"m"})
    tag: (name, o = {}) => `<md-icon name="${name}"${o.variant ? ` variant="${o.variant}"` : ""}${o.size ? ` size="${o.size}"` : ""}${o.cls ? ` class="${o.cls}"` : ""}></md-icon>`,
    register: (name, geometry, emoji = "•") => { GEOMETRY[name] = { g: geometry, emoji }; const d = document.querySelector("#md-icon-defs defs"); if (d) d.insertAdjacentHTML("beforeend", `<g id="i-${name}">${geometry}</g>`); },
    // repaint every icon on the page (after a skin or declaration change)
    repaint: () => document.querySelectorAll("md-icon").forEach(i => { delete i.dataset.painted; i.paint(); }),
  };
})(window.MD = window.MD || {});
