/* =====================================================================
   Hero slideshow: one entry per scene in web/img/hero/ (masters in assets/hero/,
   generated by scripts/gen-hero.sh). `tags` say which kits the scene belongs to,
   so the slideshow follows the kit picked on the page; `items` are the catalogue
   ids featured in the picture, shown as chips under the slide in the visitor's
   language. Same one-file, two-consumers pattern as catalogue.js: the page reads
   the global and scripts/build-site.js pre-renders the figures from it.
   ===================================================================== */
globalThis.LANDED_SLIDES = [
  { id: "bed-duvet",        tags: ["arrival"],           items: ["duvet", "pillow", "towel"] },
  { id: "kettle-mugs",      tags: ["arrival"],           items: ["kettle", "mug", "tea"] },
  { id: "night-lamp",       tags: ["arrival"],           items: ["duvet", "pillow", "lamp"] },
  { id: "bottle-bed",       tags: ["winter"],            items: ["bottle", "beanie", "socks"] },
  { id: "kitchen-pans",     tags: ["arrival"],           items: ["pan", "plate", "cutlery"] },
  { id: "window-granite",   tags: ["arrival"],           items: ["duvet", "pillow"] },
  { id: "thermal-socks",    tags: ["winter"],            items: ["thermal", "socks", "mug"] },
  { id: "studio-flat",      tags: ["arrival"],           items: ["kettle", "board", "mug"] },
  { id: "living-room-both", tags: ["arrival", "winter"], items: ["duvet", "kettle", "bottle"] },
  { id: "tea-rowies",       tags: ["winter"],            items: ["tea", "rowie", "mug"] },
  { id: "plug-desk",        tags: ["arrival"],           items: ["plug", "lamp", "mug"] },
  { id: "kitchen-morning",  tags: ["arrival"],           items: ["plate", "mug", "cutlery", "kettle"] },
  { id: "winter-window",    tags: ["winter"],            items: ["bottle", "beanie", "duvet"] },
  { id: "topper-bed",       tags: ["arrival"],           items: ["topper", "sheet", "pillow"] },
  { id: "laundry-towels",   tags: ["arrival"],           items: ["bag", "towel"] },
  { id: "house-share",      tags: ["arrival", "winter"], items: ["kettle", "mug", "tea"] },
  { id: "drying-rack",      tags: ["arrival"],           items: ["rack", "towel", "lamp"] },
  { id: "bedside-winter",   tags: ["winter"],            items: ["vitamin", "mask", "bottle"] },
];
